[package]
name = "dao"
version = "1.0.0"
authors = []

[addresses]
myAddress = "0x3423412"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
